apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: push-to-registry-template
spec:
  arguments:
    parameters:
    - name: secret
      value: <secret_key>
    - name: access
      value: <access_key>
    - name: github
      value: "<github_url>"
    - name: region
      value: <aws_region>
    - name: registry
      value: "<registry_name>"
    - name: imagename
      value: "<image_name>"

  entrypoint: generate-token
  templates:
  - name: generate-token
    steps:
    - - name: generate
        template: gen-token-bash
    - - name: push
        template: push-to-registry
        arguments:
          parameters:
          - name: token
            value: "{{steps.generate.outputs.result}}"  

  - name: gen-token-bash
    script:
      image: amazon/aws-cli
      command: [bash]
      source: |                                        
        export AWS_ACCESS_KEY_ID={{ workflow.parameters.access }} && export AWS_SECRET_ACCESS_KEY={{ workflow.parameters.secret }} && export AWS_DEFAULT_REGION={{ workflow.parameters.region }} && /usr/local/bin/aws ecr-public get-login-password --region {{ workflow.parameters.region }}
  - name: push-to-registry
    inputs:
      parameters:
      - name: token
    container:
      image: alpine/helm
      command: [sh, -c]
      args: ["apk add --update git; git clone {{ workflow.parameters.github }}; DIR_TEST=$(ls) && cd $DIR_TEST && ls && export HELM_EXPERIMENTAL_OCI=1 && echo {{ inputs.parameters.token }} | helm registry login --username AWS --password-stdin {{ workflow.parameters.registry }}; helm chart save . {{ workflow.parameters.imagename }} && helm chart push {{ workflow.parameters.imagename }}"]
