apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  creationTimestamp: "2021-05-03T08:23:09Z"
  generation: 15
  labels:
    example: "true"
    workflows.argoproj.io/creator: system-serviceaccount-default-argo-server
  name: push-to-registry-template
  namespace: default
  resourceVersion: "1520923"
  selfLink: /apis/argoproj.io/v1alpha1/namespaces/default/workflowtemplates/fantastic-python
  uid: bb410b7b-93bc-4f03-a78e-b9fbbeea744e
spec:
  arguments:
    parameters:
    - name: secret
      value: <SECRET-KEY>
    - name: access
      value: <ACCESS-KEY>
  entrypoint: Pushtoregistry
  podGC:
    strategy: OnPodCompletion
  templates:
  - container:
      args:
      - git clone https://github.com/Ishu27/test-argo-workflow.git && export AWS_ACCESS_KEY_ID={{ workflow.parameters.access }} && export AWS_SECRET_ACCESS_KEY={{ workflow.parameters.secret }} && export AWS_DEFAULT_REGION=us-east-1 && export HELM_EXPERIMENTAL_OCI=1 && /usr/local/bin/aws ecr-public get-login-password --region us-east-1 | helm registry login --username AWS --password-stdin public.ecr.aws/h8x3r6g1 && cd test-argo-workflow && helm chart save ./ public.ecr.aws/h8x3r6g1/test-argo:v2 && helm chart push public.ecr.aws/h8x3r6g1/test-argo:v2
      command:
      - sh
      - -c
      image: ishan2411/test:v2
      name: main
      resources: {}
    inputs: {}
    metadata: {}
    name: Pushtoregistry
    outputs: {}
  ttlStrategy:
    secondsAfterCompletion: 300
  workflowMetadata:
    creationTimestamp: null
    labels:
      example: "true"
