apiVersion: v1
kind: Secret
metadata:
  name: git-secret
  annotations:
    vault.security.banzaicloud.io/vault-addr: '{{ .Values.vault.address }}'
    vault.security.banzaicloud.io/vault-path: {{ .Values.vault.path }}
    vault.security.banzaicloud.io/vault-role: {{ .Values.vault.role }}
    vault.security.banzaicloud.io/vault-skip-verify: '{{ .Values.vault.skipVerify }}'
type: Opaque
stringData:
  GIT_TOKEN: vault:{{ .Values.vault.secrets.git.location }}#{{ .Values.vault.secrets.git.gitToken }}