kind: Secret
apiVersion: v1
metadata:
  name: argo-workflows-webhook-clients
stringData:
  bitbucket.org: |
    type: bitbucket
    secret: "my-uuid"
  bitbucketserver: |
    type: bitbucketserver
    secret: "shh!"
  github.com: |
    type: github
    secret: "{ SECRET NEEDS TO BE PROVIDED }"
  gitlab.com: |
    type: gitlab
    secret: "shh!"
