apiVersion: v1
kind: Secret
metadata:
  name: aws-secret
type: Opaque
stringData:
    AWS_SECRET: "aws_secret_key"
    AWS_ACCESS: "aws_accesss_key"
    USERNAME: "registry_username"
    PASSWORD: "registry_password"
