apiVersion: v1
kind: Secret
metadata:
  name: git-secret
type: Opaque
stringData:
  GIT_USERNAME: "git_username"
  GIT_TOKEN: "git_token" 
  REPO_NAME: "repo_name"     # Provide only the name of the repo
